# Map of form id to form title


form_id_map <- list(
    # GHANA R5 (2016-11-18)
    "FQ-ghr5-v12"      = "GHR5-Female-Questionnaire-v12",
    "HQ-ghr5-v12"      = "GHR5-Household-Questionnaire-v12",
    "listing-ghr5-v10" = "GHR5-Listing-v10",
    "RQ-ghr5-v12"      = "GHR5-Reinterivew-Questionnaire-v12",
    "SQ-ghr5-v12"      = "GHR5-SDP-Questionnaire-v12",
    "SQ-ghr5-v13"      = "GHR5-SDP-Questionnaire-v13",
    "sel-ghr5-v10"     = "GHR5-Selection-v10",
    "sel-ghr5-v11"     = "GHR5-Selection-v11",
    
    # NIGER R3 (2016-11-18)
    "FQ-ner3-v9"       = "NER3-Female-Questionnaire-v9",
    "HQ-ner3-v9"       = "NER3-Household-Questionnaire-v9",
    "listing-ner3-v7"  = "NER3-Listing-v7",
    "RQ-ner3-v9"       = "NER3-Reinterivew-Questionnaire-v9",
    "SQ-ner3-v9"       = "NER3-SDP-Questionnaire-v9",
    "sel-ner3-v9"      = "NER3-Selection-v9",
    
    # KENYA R5 (2016-11-18)
    "FQ-ker5-v12"      = "KER5-Female-Questionnaire-v12",
    "HQ-ker5-v12"      = "KER5-Household-Questionnaire-v12",
    "listing-ker5-v5"  = "KER5-Listing-v5",
    "RQ-ker5-v4"       = "KER5-Reinterivew-Questionnaire-v4",
    "SQ-ker5-v11"      = "KER5-SDP-Questionnaire-v11",
    "sel-ker5-v7"      = "KER5-Selection-v7",
    
    
    # FOR TESTING PURPOSES
    "SQ-rjr1-v12"      = "RJR1-SDP-Questionnaire-v12"
)


form_tags <- list(
    # GHANA R5 (2016-11-21)
    
    
    # FOR TESTING PURPOSES
    "SQ-rjr1-v12"      = list(
        start=c("<start>", "</start>"), 
        end=c("<end>", "</end>")
    )
)


form_milestones <- list(
    # GHANA R5 (2016-11-21)
    "SQ-ghr5-v13"      = c(
        "available",
        "fps_info",
        "client_feedback_note",
        "fp_methods_note",
        "fp_service_integration_note",
        "phc_consent_start",
        "workload_note",
        "prof_dev_note",
        "fac_man_note",
        "monitor_quality",
        "engagement_note",
        "supplies_note",
        "info_use_note",
        "financing_note",
        "photo_permission"
    )
)


form_prompts <- list(
    # GHANA R5 (2016-11-21)
    "SQ-ghr5-v13"      = c(
        "your_name_check",
        "name_typed",
        "system_date",
        "system_date_check",
        "manual_date",
        "level1",
        "level2",
        "EA",
        "facility_number",
        "facility_type",
        "managing_authority",
        "available",
        "consent_start",
        "consent",
        "begin_interview",
        "sign",
        "checkbox",
        "consent_warning",
        "witness_auto",
        "witness_manual",
        "facility_name",
        "facility_name_other",
        "position",
        "work_begin",
        "previously_participated",
        "services_info",
        "year_open",
        "days_open",
        "present_24hr",
        "staffing_prompt",
        "doctor_tot",
        "doctor_here",
        "nurse_tot",
        "nurse_here",
        "MA_tot",
        "MA_here",
        "ambulance_staff_tot",
        "ambulance_staff_here",
        "pharmacist_tot",
        "pharmacist_here",
        "mca_tot",
        "mca_here",
        "staff_other_tot",
        "staff_other_here",
        "knows_population_served",
        "population_served",
        "beds",
        "supervisor_visit",
        "elec_cur",
        "elec_rec",
        "water_cur",
        "water_rec",
        "handwashing_stations",
        "handwashing_observations_staff",
        "fps_info",
        "fp_offered",
        "fp_begin",
        "fp_days",
        "fp_today",
        "fp_community_health_volunteers",
        "num_fp_volunteers",
        "methods_offered",
        "mobile_outreach_6mo",
        "adolescents",
        "client_feedback_note",
        "opinions_collected_rw",
        "opinions_reported",
        "opinions_observed",
        "opinion_action_6mo",
        "fp_methods_note",
        "fp_counseled",
        "fp_provided",
        "fpc_note",
        "fpc_label",
        "fster_charged",
        "mster_charged",
        "impl_charged",
        "iud_charged",
        "inj3m_charged",
        "inj1m_charged",
        "pill_charged",
        "ec_charged",
        "ntab_charged",
        "mc_charged",
        "fc_charged",
        "dia_charged",
        "foam_charged",
        "beads_charged",
        "other_charged",
        "fpc_other",
        "fpr_note",
        "fpr_label",
        "fster_ref",
        "mster_ref",
        "impl_ref",
        "iud_ref",
        "inj3m_ref",
        "inj1m_ref",
        "pill_ref",
        "ec_ref",
        "ntab_ref",
        "mc_ref",
        "fc_ref",
        "dia_ref",
        "foam_ref",
        "beads_ref",
        "other_ref",
        "fpr_other",
        "fpf_note",
        "fster_fees",
        "mster_fees",
        "impl_fees",
        "iud_fees",
        "inj3m_fees",
        "inj1m_fees",
        "pill_fees",
        "ec_fees",
        "ntab_fees",
        "mc_fees",
        "fc_fees",
        "dia_fees",
        "foam_fees",
        "beads_fees",
        "other_fees",
        "fees_rw",
        "fees_posted",
        "implant_insert",
        "implant_remove",
        "IUD_insert",
        "IUD_remove",
        "implant_supplies",
        "IUD_suplies",
        "rega_note",
        "fster_tot",
        "mster_tot",
        "impl_tot",
        "impl_new",
        "iud_tot",
        "iud_new",
        "inj3m_tot",
        "inj3m_new",
        "inj1m_tot",
        "inj1m_new",
        "pill_tot",
        "pill_new",
        "ec_tot",
        "ec_new",
        "ntab_tot",
        "ntab_new",
        "mc_tot",
        "mc_new",
        "fc_tot",
        "fc_new",
        "dia_tot",
        "dia_new",
        "foam_tot",
        "foam_new",
        "beads_tot",
        "beads_new",
        "other_tot",
        "other_new",
        "regb_note",
        "fster_units",
        "mster_units",
        "impl_units",
        "iud_units",
        "inj3m_units",
        "inj1m_units",
        "pill_units",
        "ec_units",
        "ntab_units",
        "mc_units",
        "fc_units",
        "dia_units",
        "foam_units",
        "beads_units",
        "other_units",
        "service_stats_6mo",
        "service_charts_6mo",
        "exam_room_permission",
        "exr_note",
        "exr_labels",
        "exr_piped",
        "exr_pour",
        "exr_bucket",
        "exr_soap",
        "exr_towels",
        "exr_bin",
        "exr_sharps",
        "exr_gloves",
        "exr_disinf",
        "exr_needles",
        "exr_aud_priv",
        "exr_vis_priv",
        "exr_tables",
        "exr_fp_edu",
        "room_note",
        "room_labels",
        "room_floor",
        "room_surfaces",
        "room_area",
        "room_walls_clean",
        "room_doors",
        "room_walls_damage",
        "room_roof_damage",
        "methods_selected",
        "stockout_note",
        "stock_implants",
        "stockout_days_implants",
        "stockout_3mo_implants",
        "stock_IUD",
        "stockout_days_IUD",
        "stockout_3mo_IUD",
        "stock_injectables_3mo",
        "stockout_days_injectables_3mo",
        "stockout_3mo_injectables_3mo",
        "stock_injectables_1mo",
        "stockout_days_injectables_1mo",
        "stockout_3mo_injectables_1mo",
        "stock_pills",
        "stockout_days_pills",
        "stockout_3mo_pills",
        "stock_ec",
        "stockout_days_ec",
        "stockout_3mo_ec",
        "stock_ntab",
        "stockout_days_ntab",
        "stockout_3mo_ntab",
        "stock_male_condoms",
        "stockout_days_male_condoms",
        "stockout_3mo_male_condoms",
        "stock_female_condoms",
        "stockout_days_female_condoms",
        "stockout_3mo_female_condoms",
        "stock_diaphragm",
        "stockout_days_diaphragm",
        "stockout_3mo_diaphragm",
        "stock_foam",
        "stockout_days_foam",
        "stockout_3mo_foam",
        "stock_beads",
        "stockout_days_beads",
        "stockout_3mo_beads",
        "stock_other",
        "stockout_days_other",
        "stockout_3mo_other",
        "storage_check",
        "storage_prompt",
        "storage_labels",
        "protected_floor",
        "protected_water",
        "protected_sun",
        "protected_pests",
        "fp_service_integration_note",
        "antenatal",
        "postpartum_rw",
        "fp_during_postpartum",
        "postabortion_discussion",
        "fp_during_postabortion",
        "HIV_services",
        "STI_services",
        "HIV_condom",
        "HIV_other_fp",
        "HIV_info_elsewhere",
        "HIV_referred_where",
        "phc_consent_start",
        "phc_position",
        "separate_opd",
        "phc_preamble",
        "defined_pop",
        "pop_count",
        "pop_defined",
        "pop_defined_other",
        "measure_coverage",
        "tracking",
        "disease",
        "methods_used",
        "methods_used_other",
        "results_collected",
        "community_health_workers",
        "num_health_workers",
        "chw_outreach",
        "chw_supervise",
        "chw_freq",
        "chw_freq_int",
        "workload_note",
        "provider_time",
        "register_permission",
        "register_count",
        "register_estimate",
        "prof_dev_note",
        "review_performance",
        "cadres_reviewed",
        "cadres_reviewed_other",
        "criteria",
        "criteria_detail",
        "criteria_detail_other",
        "supervision",
        "supervision_other",
        "trainings",
        "decide_training",
        "left",
        "fac_man_note",
        "formal_training",
        "formal_type",
        "formal_type_other",
        "typical_day_tot",
        "typical_day_note",
        "patient_flow",
        "supervise_staff",
        "manage_budget",
        "ensure_drugs",
        "treat_patients",
        "manage_relations",
        "yest_other",
        "hr_ack",
        "scenario_note",
        "first_day",
        "guidelines",
        "antibiotics",
        "authority_note",
        "drugs_say",
        "you_drugs_say",
        "recruitment_say",
        "you_recruitment_say",
        "promoted_say",
        "you_promoted_say",
        "discipline_say",
        "you_discipline_say",
        "paint_say",
        "you_paint_say",
        "absence_say",
        "you_absence_say",
        "priorities_say",
        "you_priorities_say",
        "discretionary_say",
        "you_discretionary_say",
        "monitor_quality",
        "quality_activities",
        "who_quality",
        "statistics",
        "monitor_agree",
        "engagement_note",
        "cab_meet",
        "cab_follow",
        "regular_attend",
        "share_info",
        "how_share",
        "how_share_other",
        "opinion_drive",
        "supplies_note",
        "phc_staff_note",
        "phc_doctors",
        "phc_nurses",
        "phc_assistants",
        "phc_pharms",
        "phc_others",
        "ambulance",
        "fuel",
        "resources_note",
        "adult_scale",
        "adult_scale_func",
        "child_scale",
        "child_scale_func",
        "sphyg",
        "sphyg_func",
        "thermom",
        "thermom_func",
        "steth",
        "steth_func",
        "sterilize_equip",
        "non_elec_equip",
        "drugs_avail",
        "drugs_check",
        "info_use_note",
        "single_record",
        "record_format",
        "record_format_other",
        "record_describe",
        "record_describe_other",
        "financing_note",
        "financing_begin_note",
        "fees_displayed",
        "fees_exempt",
        "fees_check",
        "annual_budget",
        "books_track",
        "internal_funds_tot",
        "internal_funds",
        "funds_check",
        "external_audit",
        "nhis_approved",
        "reimburse_unit",
        "reimburse_label",
        "reimburse_int",
        "photo_permission",
        "thankyou",
        "SDP_photo",
        "location",
        "times_visited",
        "survey_language",
        "SDP_result"
    ),
    
    # FOR TESTING PURPOSES
    "SQ-rjr1-v12"      = c(
        "your_name",
        "system_date",
        "EA",
        "position",
        "fp_begin", 
        "XYZ"
    )
)
